version: '3.8'

services:
  bully:
    build: .
    command: python algorithms/bully.py 1
    volumes:
      - .:/app

  ring:
    build: .
    command: python algorithms/ring.py 1
    volumes:
      - .:/app

  proof_of_work:
    build: .
    command: python algorithms/proof_of_work.py 1
    volumes:
      - .:/app

  proof_of_stake:
    build: .
    command: python algorithms/proof_of_stake.py 1
    volumes:
      - .:/app

  visualizer:
    build: .
    command: python visualizer.py
    volumes:
      - .:/app
    depends_on:
      - bully
      - ring
      - proof_of_work
      - proof_of_stake
